packages:
  - 'packages/*'

allowBuilds:
  '@swc/core': true
  esbuild: true
  nx: true
  sqlite3: true
  unrs-resolver: true
overrides:
  '@vilancer/filelinks-core': link:packages/core
  '@vilancer/filelinks': link:packages/cli
